package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// rigClaudeMD is one of the agent-facing breadcrumbs rig drops at the basedir
// root. Unlike a static skill it can carry the live task and repo set.
const rigClaudeMDName = "CLAUDE.md"

const rigAgentsMDName = "AGENTS.md"

// writeRigClaudeMD renders the basedir CLAUDE.md from the manifest. It's
// regenerated whenever the repo set changes (initial up, every rig add) so the
// repo list never drifts. Kept deliberately thin: auto-loaded context should
// earn its tokens, so this states the rig model and the live facts and stops.
func writeRigClaudeMD(basedir string, m manifest) error {
	body := renderRigInstructions(m)
	return os.WriteFile(filepath.Join(basedir, rigClaudeMDName), []byte(body), 0o644)
}

// writeRigAgentInstructions writes the same live rig context in each agent's
// native shape. Claude and Codex use parent instruction files; Antigravity's
// workspace rules live under .agents/rules. The launch prompt also points to
// AGENTS.md explicitly, covering clients that stop discovery at the repo cwd.
func writeRigAgentInstructions(basedir string, m manifest) error {
	body := []byte(renderRigInstructions(m))
	for _, name := range []string{rigClaudeMDName, rigAgentsMDName} {
		if err := os.WriteFile(filepath.Join(basedir, name), body, 0o644); err != nil {
			return err
		}
	}
	rulesDir := filepath.Join(basedir, ".agents", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(rulesDir, "rig.md"), body, 0o644)
}

func renderRigInstructions(m manifest) string {
	var b strings.Builder

	heading := m.ID
	if m.Title != "" {
		heading = fmt.Sprintf("%s: %s", m.ID, m.Title)
	}
	fmt.Fprintf(&b, "# Rig %s\n\n", heading)
	b.WriteString("You are working inside a **rig**: a task-shaped workspace dedicated to this\n")
	b.WriteString("one task, holding every repo the task touches.\n\n")

	b.WriteString("- The repos here are **jj workspaces**, not plain git checkouts. Use `jj`\n")
	b.WriteString("  (`jj st`, `jj diff`, `jj log`), not `git`. Git commands fail here with\n")
	b.WriteString("  \"not a git repository\". The `jj` skill has the full playbook.\n")

	if len(m.Repos) > 0 {
		b.WriteString("- Repos in this rig:\n")
		subdirs := make([]string, 0, len(m.Repos))
		for subdir := range m.Repos {
			subdirs = append(subdirs, subdir)
		}
		sort.Strings(subdirs)
		for _, subdir := range subdirs {
			fmt.Fprintf(&b, "  - `%s` (./%s)\n", m.Repos[subdir], subdir)
		}
	}

	b.WriteString("- The main tmux window holds the task-level agent plus the currently relevant\n")
	b.WriteString("  Recto diff. Every repo has one persistent Recto; inactive ones are full-window\n")
	b.WriteString("  tabs. Use `rig recto <repo>` to pull one beside the agent, or combine the\n")
	b.WriteString("  promotion with a Recto command, e.g. `rig recto cloud focus src/app.go:42`.\n")
	b.WriteString("  Do not manipulate tmux panes directly. For an ad hoc shell, split from a\n")
	b.WriteString("  repo's Recto so tmux inherits the correct working directory.\n")
	b.WriteString("- Bring in another repo the task touches with `rig add owner/repo`; tear the\n")
	b.WriteString("  whole rig back down with `rig down`.\n\n")

	b.WriteString("<!-- generated by rig; regenerated as repos are added. edits get overwritten. -->\n")

	return b.String()
}
