package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// rigClaudeMD is the agent-facing breadcrumb rig drops at the basedir root. It
// auto-loads as parent context for any agent whose cwd is a repo subdir, which
// is exactly the worker agents `rig up` spawns into the session. Unlike a
// static skill it can carry the live facts — which task, which repos — and it
// stacks above each repo's own checked-in CLAUDE.md without clobbering it.
const rigClaudeMDName = "CLAUDE.md"

// writeRigClaudeMD renders the basedir CLAUDE.md from the manifest. It's
// regenerated whenever the repo set changes (initial up, every rig add) so the
// repo list never drifts. Kept deliberately thin: auto-loaded context should
// earn its tokens, so this states the rig model and the live facts and stops.
func writeRigClaudeMD(basedir string, m manifest) error {
	var b strings.Builder

	heading := m.ID
	if m.Title != "" {
		heading = fmt.Sprintf("%s: %s", m.ID, m.Title)
	}
	fmt.Fprintf(&b, "# Rig %s\n\n", heading)
	b.WriteString("You are working inside a **rig**: a task-shaped workspace dedicated to this\n")
	b.WriteString("one task, holding every repo the task touches.\n\n")

	b.WriteString("- The repos here are **jj workspaces**, not plain git checkouts. Use `jj`\n")
	b.WriteString("  (`jj st`, `jj diff`, `jj log`), not `git`. Git commands fail here with\n")
	b.WriteString("  \"not a git repository\". The `jj` skill has the full playbook.\n")

	if len(m.Repos) > 0 {
		b.WriteString("- Repos in this rig:\n")
		subdirs := make([]string, 0, len(m.Repos))
		for subdir := range m.Repos {
			subdirs = append(subdirs, subdir)
		}
		sort.Strings(subdirs)
		for _, subdir := range subdirs {
			fmt.Fprintf(&b, "  - `%s` (./%s)\n", m.Repos[subdir], subdir)
		}
	}

	b.WriteString("- The recto pane (right of the session) live-previews uncommitted diffs as\n")
	b.WriteString("  you work, so you can see the shape of a change without running `jj diff`.\n")
	b.WriteString("- Bring in another repo the task touches with `rig add owner/repo`; tear the\n")
	b.WriteString("  whole rig back down with `rig down`.\n\n")

	b.WriteString("<!-- generated by rig; regenerated as repos are added. edits get overwritten. -->\n")

	return os.WriteFile(filepath.Join(basedir, rigClaudeMDName), []byte(b.String()), 0o644)
}
